name: Build

permissions:
  contents: write
  packages: write

on: 
  push:
  pull_request:
  release:
    types: [created]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
      - name: Build for macOS
        run: npm run ${{ github.event_name == 'release' && 'release:mac' || 'build:mac' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build-dmg
          path: dist/*.dmg
          if-no-files-found: warn
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build-pkg
          path: dist/*.pkg
          if-no-files-found: warn

  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
      - name: Build for Windows
        run: npm run ${{ github.event_name == 'release' && 'release:win' || 'build:win' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/*.exe

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: npm install
      - name: Build for Linux
        run: npm run ${{ github.event_name == 'release' && 'release:linux' || 'build:linux' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/*.AppImage
